Update README.en.md
sastrawi/sastrawi pull request #29
Opened 2016-10-25 10:27 UTC by denipramulia

Change link "README" in README.en.md because it doesn't change to other link (still in the same link)
to link "README.md" 
Change word "English" to "Indonesia" because in link README.md, mostly use Indonesia Languange.

2016-10-25 10:27 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/sastrawi/sastrawi/inspections/8c8e3cd2-32cb-42dc-a9d5-9f8a3a91b14a) was created.

2016-10-25 10:33 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/sastrawi/sastrawi/inspections/8c8e3cd2-32cb-42dc-a9d5-9f8a3a91b14a) completed: **No new issues**

2016-10-25 11:43 UTC, jayvdb commented on README.en.md
> +For more information in Indonesia, see [README](https://github.com/andylib/sastrawi/blob/master/README.md).
"Indonesia" -> "Indonesian"

2016-10-25 11:49 UTC, scrutinizer-notifier commented
A [new inspection](https://scrutinizer-ci.com/g/sastrawi/sastrawi/inspections/0e696da8-3610-409a-8f25-dd65f5b3dfef) was created.

2016-10-25 11:52 UTC, jayvdb requested changes
Please `git squash` your two commits into one commit , and then `git push -f` to push your new commit into this pull request.

2016-10-25 11:55 UTC, scrutinizer-notifier commented
The [inspection](https://scrutinizer-ci.com/g/sastrawi/sastrawi/inspections/0e696da8-3610-409a-8f25-dd65f5b3dfef) completed: **No new issues**

2016-10-25 11:55 UTC, denipramulia commented
@jayvdb sorry mr.John, but i dont know how to git squash before..

2016-10-25 13:03 UTC, andylibrian commented
Hi @denipramulia, thanks for your contribution. Also thanks @jayvdb for reviewing.

@denipramulia, please squash those commits into a single one. You can use `git rebase -i`.

- https://help.github.com/articles/about-git-rebase/
- http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

2016-10-27 00:19 UTC, jayvdb commented
Also see the relevant untranslated ProGit2 chapter ["Rewriting History"](https://github.com/progit/progit2-id/blob/master/book/07-git-tools/sections/rewriting-history.asc)

2018-01-10 14:30 UTC, closed without merging